#ifndef LIBP101_CONVERT_ERRORS_H
#define LIBP101_CONVERT_ERRORS_H

enum p101_convert_error
{
    P101_CONVERT_ERROR_SYNTAX = 1,
    P101_CONVERT_ERROR_RANGE,
    P101_CONVERT_ERROR_ADDRESS
};

#endif    // LIBP101_CONVERT_ERRORS_H
